/** 
 * Access Identifier: `Public` this accessible from anywhere
 * Access Identifier: `Private` this accessible from anywhere
 * Access Identifier: `Global` this accessible from anywhere
 * Access Identifier: `Default` this accessible from anywhere
 * Signature & Definition: 
 * Access_Identifier class_keyword Class_Name {}
 * */ 
public class Vehicle {
    /**
     * numOfWheels
     * Types of Variable
     * Pre Defined: String, Integer, Decimal, Boolean
     * Signature & Definition: 
     * Access_Identifier variable_type variable_name
     */
    private String wheel_type;
    private Integer numOfWheels;
    private Boolean isElectric;

    


}