public with sharing class Happyanniversary {
    public static String name;
    public static Integer tareekh;
    public static void barakallahufeekum(){
        name='Gulshana Raees';
        tareekh=19;
        System.debug('Name is '+name+' and tareekh is'+tareekh+'');
    
        name='Tarique shamim';
        tareekh=19;
        System.debug('Name is '+name+' and tareekh is'+tareekh+'');
    }
    

    }
