public with sharing class Merg {
    public static List<Integer> x=new List<Integer>{1,2,3,4,5};
    public static List<Integer> y=new List<Integer>{6,7,1,5,3};
    public static void mer(){
        Integer size=x.size();
        Integer result=0;
        for(Integer i=0; i<size; i++){
            Integer no=X[i];
           for(Integer j=0; j<size; j++){
            Integer num=Y[j];
            if(X[i] == Y[j]){
                result=X[i];
                system.debug(result);
            }
             
            
          }
        }
         
    }
}